name: build

on:
  push:
    branches:
      - 'main'

env:
  DOCKERHUB_USERNAME: 7366766@qq.com

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build backend and push
        uses: docker/build-push-action@v3
        with:
          context: getting-started
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/getting-started:${{ steps.vars.outputs.sha_short }}
      - name: Build frontend and push
        uses: docker/build-push-action@v3
        with:
          context: hello-world-flask
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/hello-world-flask:${{ steps.vars.outputs.sha_short }}